spring:
  application:
    name: insurance-configuration
  datasource:
    url: jdbc:postgresql://localhost:5433/bancassurance-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    jdbc:
      dialect: postgresql
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/Bancassurance/protocol/openid-connect/certs
          issuer-uri: http://localhost:9090/realms/Bancassurance

server:
  port: 8091

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.hibernate: DEBUG